services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRE_DB=postgre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local